// users/devone/tests/queries.test.ts
//
// Fixtures are built here at exact timestamps rather than generated by
// seed.py — a month-boundary test cannot be written against a generator whose
// timestamps float with the wall clock, and seed.py exists to make a browser
// show something plausible, not to be an oracle.
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import Database from 'better-sqlite3-multiple-ciphers'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import type { UserDb } from '@/lib/db/userDb'
import {
  eatingOutThisMonthCents,
  monthRange,
  recentTransactions,
} from '@/users/devone/queries'

const SCHEMA = resolve(__dirname, '..', 'schema.sql')

let dir: string
let db: UserDb

function add(row: {
  merchant: string
  category: string
  amount_cents: number
  at: number
}) {
  db.prepare(
    'INSERT INTO transactions (merchant, category, amount_cents, at) VALUES (?, ?, ?, ?)',
  ).run(row.merchant, row.category, row.amount_cents, row.at)
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'stairwell-devone-'))
  db = new Database(join(dir, 'synthetic.db'))
  db.exec(readFileSync(SCHEMA, 'utf8'))
})

afterEach(() => {
  db.close()
  rmSync(dir, { recursive: true, force: true })
})

// 15 March 2026, 12:00 local. Local, not UTC: monthRange builds its bounds
// from the local calendar, so a UTC literal here would put the test and the
// code in different months for anyone west of Greenwich.
const MID_MARCH = new Date(2026, 2, 15, 12, 0, 0).getTime()

describe('monthRange', () => {
  it('spans the calendar month containing now', () => {
    const { start, end } = monthRange(MID_MARCH)
    expect(new Date(start).getTime()).toBe(new Date(2026, 2, 1).getTime())
    expect(new Date(end).getTime()).toBe(new Date(2026, 3, 1).getTime())
  })

  it('rolls the year over in December', () => {
    const { end } = monthRange(new Date(2026, 11, 15).getTime())
    expect(new Date(end).getTime()).toBe(new Date(2027, 0, 1).getTime())
  })
})

describe('eatingOutThisMonthCents', () => {
  it('returns 0 on an empty table rather than null', () => {
    // COALESCE, not a null that renders as "$NaN" on the friend's page.
    expect(eatingOutThisMonthCents(db, MID_MARCH)).toBe(0)
  })

  it('sums only the eating-out rows inside the month', () => {
    add({ merchant: 'COFFEE PALACE TEST', category: 'eating out', amount_cents: 500, at: MID_MARCH })
    add({ merchant: 'BURRITO BARN TEST', category: 'eating out', amount_cents: 1200, at: MID_MARCH })
    add({ merchant: 'GROCERY WORLD TEST', category: 'groceries', amount_cents: 9000, at: MID_MARCH })
    expect(eatingOutThisMonthCents(db, MID_MARCH)).toBe(1700)
  })

  it('excludes the last millisecond of the previous month', () => {
    add({
      merchant: 'COFFEE PALACE TEST',
      category: 'eating out',
      amount_cents: 500,
      at: new Date(2026, 2, 1).getTime() - 1,
    })
    expect(eatingOutThisMonthCents(db, MID_MARCH)).toBe(0)
  })

  it('includes the first millisecond of this month', () => {
    add({
      merchant: 'COFFEE PALACE TEST',
      category: 'eating out',
      amount_cents: 500,
      at: new Date(2026, 2, 1).getTime(),
    })
    expect(eatingOutThisMonthCents(db, MID_MARCH)).toBe(500)
  })

  it('excludes the first millisecond of next month', () => {
    // Without an upper bound this passes anyway for a clock-relative "now",
    // and then silently counts future-dated rows the day one appears.
    add({
      merchant: 'COFFEE PALACE TEST',
      category: 'eating out',
      amount_cents: 500,
      at: new Date(2026, 3, 1).getTime(),
    })
    expect(eatingOutThisMonthCents(db, MID_MARCH)).toBe(0)
  })
})

describe('recentTransactions', () => {
  it('returns the newest first, capped at ten', () => {
    for (let i = 0; i < 15; i++) {
      add({
        merchant: `MERCHANT ${i} TEST`,
        category: 'eating out',
        amount_cents: 100 + i,
        at: MID_MARCH + i,
      })
    }
    const rows = recentTransactions(db)
    expect(rows).toHaveLength(10)
    expect(rows[0]!.merchant).toBe('MERCHANT 14 TEST')
    expect(rows[9]!.merchant).toBe('MERCHANT 5 TEST')
  })

  it('honours an explicit limit', () => {
    for (let i = 0; i < 5; i++) {
      add({ merchant: `M${i} TEST`, category: 'eating out', amount_cents: 1, at: MID_MARCH + i })
    }
    expect(recentTransactions(db, 2)).toHaveLength(2)
  })

  it('returns an empty array on an empty table', () => {
    expect(recentTransactions(db)).toEqual([])
  })

  it('breaks a same-timestamp tie by insertion order, newest row last inserted first', () => {
    // A real Plaid import posts a batch of transactions sharing one
    // timestamp, and without a deterministic order the list would reshuffle
    // between renders of the exact same data.
    //
    // What this test PINS: the tiebreak direction. `id DESC` must mean
    // newest-inserted-first; flip it to `id ASC` and only this test goes
    // red (verified by hand).
    //
    // What it CANNOT pin: dropping `, id DESC` entirely. transactions_at
    // indexes (at), which SQLite stores as (at, rowid); EXPLAIN QUERY PLAN
    // shows `ORDER BY at DESC` alone already resolves via
    // `SCAN transactions USING INDEX transactions_at` — the same plan as
    // with the explicit tiebreak — so with that index in place the two
    // queries are indistinguishable and no test can tell them apart. The
    // clause is redundant given TODAY'S index, and is kept anyway so the
    // order stays a property of the query rather than of whichever index
    // happens to exist — a future schema change that drops or reshapes
    // transactions_at would otherwise make the order unspecified with no
    // test able to notice.
    add({ merchant: 'FIRST TEST', category: 'eating out', amount_cents: 100, at: MID_MARCH })
    add({ merchant: 'SECOND TEST', category: 'eating out', amount_cents: 200, at: MID_MARCH })
    add({ merchant: 'THIRD TEST', category: 'eating out', amount_cents: 300, at: MID_MARCH })
    const rows = recentTransactions(db)
    expect(rows.map((r) => r.merchant)).toEqual(['THIRD TEST', 'SECOND TEST', 'FIRST TEST'])
  })
})
