// users/devtwo/tests/queries.test.ts
//
// Fixtures are built here at exact day keys rather than generated by seed.py:
// a streak boundary cannot be tested against a generator whose days move with
// the wall clock, and seed.py exists to make a browser show something
// plausible, not to be an oracle.
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import Database from 'better-sqlite3-multiple-ciphers'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import type { UserDb } from '@/lib/db/userDb'
import { applyUserMigrations } from '@/tests/support/userMigrations'
import {
  currentStreak,
  last14,
  last30,
  walkedOn,
} from '@/users/devtwo/queries'


let dir: string
let db: UserDb

function walked(...days: string[]) {
  const stmt = db.prepare('INSERT OR IGNORE INTO walks (day, at) VALUES (?, ?)')
  for (const day of days) stmt.run(day, 1)
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'stairwell-devtwo-'))
  db = new Database(join(dir, 'synthetic.db'))
  applyUserMigrations(db, 'devtwo')
})

afterEach(() => {
  db.close()
  rmSync(dir, { recursive: true, force: true })
})

// The `dayKeyOf` tests that stood here are gone with the export.
//
// They asserted that it returned the HOST's local calendar day — which was
// true, and was the bug: the host is a UTC droplet, so a friend's evening tap
// was filed as tomorrow. `today` is handed in as a prop now
// (lib/dashboard/contract.ts) and the zone-aware version is pinned in
// tests/time/dayKey.test.ts.
//
// What survived into `shift` is pure calendar arithmetic — "what is 13 days
// before 2026-03-01" — which never reads a clock and is therefore correct in
// any zone. It is exercised through the exported functions below rather than
// directly, because it is private for the same reason `dayKeyOf` is: nothing
// outside this file should be able to turn a number into a day.
describe('calendar arithmetic across boundaries', () => {
  it('walks a streak backwards over a month boundary', () => {
    walked('2026-03-01', '2026-02-28', '2026-02-27')
    expect(currentStreak(db, '2026-03-01')).toBe(3)
  })

  it('walks a streak backwards over a year boundary', () => {
    walked('2026-01-01', '2025-12-31', '2025-12-30')
    expect(currentStreak(db, '2026-01-01')).toBe(3)
  })

  it('builds a 14-day window that crosses a month boundary in order', () => {
    const days = last14(db, '2026-03-05').map((d) => d.day)
    expect(days).toHaveLength(14)
    expect(days[0]).toBe('2026-02-20')
    expect(days[13]).toBe('2026-03-05')
    expect([...days].sort()).toEqual(days)
  })
})

describe('walkedOn', () => {
  it('is false on an empty table and true after a walk', () => {
    expect(walkedOn(db, '2026-08-13')).toBe(false)
    walked('2026-08-13')
    expect(walkedOn(db, '2026-08-13')).toBe(true)
  })
})

describe('currentStreak', () => {
  it('counts consecutive days ending today', () => {
    walked('2026-08-11', '2026-08-12', '2026-08-13')
    expect(currentStreak(db, '2026-08-13')).toBe(3)
  })

  it('survives today being unlogged if yesterday was — the grace day', () => {
    // From the confirmed spec: "ending today or yesterday". A streak must not
    // break at 00:01 before the day has had a chance to happen.
    walked('2026-08-11', '2026-08-12')
    expect(currentStreak(db, '2026-08-13')).toBe(2)
  })

  it('is zero when neither today nor yesterday was walked', () => {
    walked('2026-08-01', '2026-08-02')
    expect(currentStreak(db, '2026-08-13')).toBe(0)
  })

  it('stops at a gap rather than counting every logged day', () => {
    walked('2026-08-01', '2026-08-12', '2026-08-13')
    expect(currentStreak(db, '2026-08-13')).toBe(2)
  })

  it('crosses a month boundary', () => {
    walked('2026-07-31', '2026-08-01')
    expect(currentStreak(db, '2026-08-01')).toBe(2)
  })

  it('is zero on an empty table', () => {
    expect(currentStreak(db, '2026-08-13')).toBe(0)
  })
})

describe('last30', () => {
  it('counts the window inclusive of today, 30 days wide', () => {
    walked('2026-08-13', '2026-08-12', '2026-08-11')
    const result = last30(db, '2026-08-13')
    expect(result.total).toBe(30)
    expect(result.walked).toBe(3)
    expect(result.percent).toBe(10)
  })

  it('excludes the day that falls just outside the window', () => {
    // 30 days ending 2026-08-13 starts on 2026-07-15. 07-14 is outside.
    walked('2026-07-14')
    expect(last30(db, '2026-08-13').walked).toBe(0)
  })

  it('includes the first day inside the window', () => {
    walked('2026-07-15')
    expect(last30(db, '2026-08-13').walked).toBe(1)
  })

  it('is 0% on an empty table rather than NaN', () => {
    expect(last30(db, '2026-08-13')).toEqual({ walked: 0, total: 30, percent: 0 })
  })
})

describe('last14', () => {
  it('returns 14 entries, oldest first, ending today', () => {
    const row = last14(db, '2026-08-13')
    expect(row).toHaveLength(14)
    expect(row[0]!.day).toBe('2026-07-31')
    expect(row[13]!.day).toBe('2026-08-13')
  })

  it('marks only the logged days', () => {
    walked('2026-08-13', '2026-08-10')
    const row = last14(db, '2026-08-13')
    expect(row[13]!.walked).toBe(true)
    expect(row[10]!.walked).toBe(true)
    expect(row[12]!.walked).toBe(false)
  })
})
